nginx:
  image: nginx:1.9
  ports:
    - "80:80"
    - "443:443"
  links:
    - stash
    - jira
    - confluence
    - crowd
  volumes:
    - nginx.conf:/etc/nginx/nginx.conf

stash:
  extends:
    file: atlassian-stash/stash.yml
    service: stash
  links:
    - database
  volumes:
    - atlassian-stash/home:/opt/stash-home

jira:
  extends:
    file: atlassian-jira/jira.yml
    service: jira
  links:
    - database
  volumes:
    - atlassian-jira/home:/opt/jira-home

confluence:
  extends:
    file: atlassian-confluence/confluence.yml
    service: confluence
  links:
    - database
  volumes:
    - atlassian-confluence/home:/opt/confluence-home

crowd:
  extends:
    file: atlassian-crowd/crowd.yml
    service: crowd
  links:
    - database
  volumes:
    - atlassian-crowd/home:/opt/crowd-home

bamboo:
  extends:
    file: atlassian-bamboo/bamboo.yml
    service: crowd
  links:
    - database
  volumes:
    - atlassian-bamboo/home:/opt/bamboo-home

database:
  image: postgres:9.4
  volumes:
    - atlassian-confluence/setup-confluence-db.sh:/docker-entrypoint-initdb.d/setup-confluence-db.sh
    - atlassian-crowd/setup-crowd-db.sh:/docker-entrypoint-initdb.d/setup-crowd-db.sh
    - atlassian-jira/setup-jira-db.sh:/docker-entrypoint-initdb.d/setup-jira-db.sh
    - atlassian-stash/setup-stash-db.sh:/docker-entrypoint-initdb.d/setup-stash-db.sh
    - atlassian-bamboo/setup-bamboo-db.sh:/docker-entrypoint-initdb.d/setup-bamboo-db.sh
    - tmp:/tmp/dumps # import backup
