bamboo:
  image: mhubig/atlassian-bamboo
  restart: always
  links:
    - database
  volumes:
    - home:/opt/bamboo-home

database:
  image: postgres:9.4
  restart: always
  volumes:
    - data:/var/lib/postgresql/data
    - setup-bamboo-db.sh:/docker-entrypoint-initdb.d/setup-bamboo-db.sh
