stash:
  extends:
    file: stash.yml
    service: stash
  restart: always
  links:
    - database
  volumes:
    - home:/opt/stash-home

database:
  image: postgres:9.4
  restart: always
  volumes:
    - data:/var/lib/postgresql/data
    - setup-stash-db.sh:/docker-entrypoint-initdb.d/setup-stash-db.sh
