confluence:
  extends:
    file: confluence.yml
    service: confluence
  restart: always
  links:
    - database
  volumes:
    - home:/opt/confluence-home

database:
  image: postgres:9.4
  restart: always
  volumes:
    - data:/var/lib/postgresql/data
    - setup-confluence-db.sh:/docker-entrypoint-initdb.d/setup-confluence-db.sh
